export enum Constants {
  GET_PHOTOS = "GET_PHOTOS",
  GET_PHOTOS_SUCCESS = "GET_PHOTOS_SUCCESS",
  GET_PHOTOS_ERROR = "GET_PHOTOS_ERROR",
  GET_BACKGROUND = "GET_BACKROUND",
  GET_BACKGROUND_SUCCESS = "GET_BACKROUND_SUCCESS",
  GET_BACKGROUND_ERROR = "GET_BACKROUND_ERROR",
  SHOW_MODAL = "SHOW_MODAL",
  HIDE_MODAL = "HIDE_MODAL",
  GET_SUGGESTIONS = "GET_SUGGESTIONS",
  NEXT_PAGE = "NEXT_PAGE",
}
